# Generated by Django 5.0.1 on 2024-02-20 13:43

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(upload_to='covers/')),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('av', 'В наличии'), ('nv', 'Нет в наличии')], max_length=2)),
                ('category', models.ForeignKey(on_delete=models.SET(app.models.Book.get_first_category), to='app.category')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
