# Generated by Django 5.0.1 on 2024-02-20 13:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=app.models.Book.get_first_category, on_delete=models.SET(app.models.Book.get_first_category), to='app.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('av', 'В наличии'), ('nv', 'Нет в наличии')], default='av', max_length=2),
        ),
    ]
